-- Run this in the Supabase SQL editor after creating the admin auth user.
-- Assign the user app_metadata.role = "admin" from a trusted server or the
-- Supabase dashboard. Never let users update their own app_metadata.

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  description text,
  badge text,
  offer_price numeric,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  size_key text not null,
  label text not null,
  weight text not null,
  price numeric not null,
  sort_order integer not null default 0,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  unique (product_id, size_key)
);

create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  alt_text text,
  caption text,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = excluded.public;

-- Upgrade the earlier standalone-offer structure if it already exists.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'offers'
      and column_name = 'product_id' and udt_name <> 'uuid'
  ) then
    alter table public.offers drop column product_id;
  end if;
end $$;
alter table public.offers add column if not exists product_id uuid references public.products(id) on delete cascade;
alter table public.offers add column if not exists offer_price numeric;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'offers' and column_name = 'title'
  ) then
    alter table public.offers alter column title drop not null;
  end if;
end $$;

alter table public.products enable row level security;
alter table public.offers enable row level security;
alter table public.reviews enable row level security;
alter table public.product_variants enable row level security;
alter table public.gallery_images enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);

drop policy if exists "Public can read offers" on public.offers;
create policy "Public can read offers"
on public.offers for select
to anon, authenticated
using (true);

drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
on public.reviews for select
to anon, authenticated
using (true);

drop policy if exists "Public can read product variants" on public.product_variants;
create policy "Public can read product variants"
on public.product_variants for select
to anon, authenticated
using (true);

drop policy if exists "Public can read gallery images" on public.gallery_images;
create policy "Public can read gallery images"
on public.gallery_images for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can insert offers" on public.offers;
create policy "Admins can insert offers"
on public.offers for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update offers" on public.offers;
create policy "Admins can update offers"
on public.offers for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete offers" on public.offers;
create policy "Admins can delete offers"
on public.offers for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can insert reviews" on public.reviews;
create policy "Admins can insert reviews"
on public.reviews for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update reviews" on public.reviews;
create policy "Admins can update reviews"
on public.reviews for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete reviews" on public.reviews;
create policy "Admins can delete reviews"
on public.reviews for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can insert product variants" on public.product_variants;
create policy "Admins can insert product variants"
on public.product_variants for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update product variants" on public.product_variants;
create policy "Admins can update product variants"
on public.product_variants for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete product variants" on public.product_variants;
create policy "Admins can delete product variants"
on public.product_variants for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can insert gallery images" on public.gallery_images;
create policy "Admins can insert gallery images"
on public.gallery_images for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update gallery images" on public.gallery_images;
create policy "Admins can update gallery images"
on public.gallery_images for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete gallery images" on public.gallery_images;
create policy "Admins can delete gallery images"
on public.gallery_images for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Public can read image files" on storage.objects;
create policy "Public can read image files"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'images');

drop policy if exists "Admins can upload image files" on storage.objects;
create policy "Admins can upload image files"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'images'
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "Admins can update image files" on storage.objects;
create policy "Admins can update image files"
on storage.objects for update
to authenticated
using (
  bucket_id = 'images'
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  bucket_id = 'images'
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "Admins can delete image files" on storage.objects;
create policy "Admins can delete image files"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'images'
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);
