-- Run this in the Supabase SQL editor after creating the admin auth user.
-- Assign the user app_metadata.role = "admin" from a trusted server or the
-- Supabase dashboard. Never let users update their own app_metadata.

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  description text,
  badge text,
  offer_price numeric,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Upgrade the earlier standalone-offer structure if it already exists.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'offers'
      and column_name = 'product_id' and udt_name <> 'uuid'
  ) then
    alter table public.offers drop column product_id;
  end if;
end $$;
alter table public.offers add column if not exists product_id uuid references public.products(id) on delete cascade;
alter table public.offers add column if not exists offer_price numeric;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'offers' and column_name = 'title'
  ) then
    alter table public.offers alter column title drop not null;
  end if;
end $$;

alter table public.products enable row level security;
alter table public.offers enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);

drop policy if exists "Public can read offers" on public.offers;
create policy "Public can read offers"
on public.offers for select
to anon, authenticated
using (true);

drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
on public.reviews for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can insert offers" on public.offers;
create policy "Admins can insert offers"
on public.offers for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update offers" on public.offers;
create policy "Admins can update offers"
on public.offers for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete offers" on public.offers;
create policy "Admins can delete offers"
on public.offers for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can insert reviews" on public.reviews;
create policy "Admins can insert reviews"
on public.reviews for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can update reviews" on public.reviews;
create policy "Admins can update reviews"
on public.reviews for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins can delete reviews" on public.reviews;
create policy "Admins can delete reviews"
on public.reviews for delete
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
